### ISSUE TITLE
tsutils doesn't find typescript in monorepo

### ISSUE THREAD

**Issue by forgetso** [ajafff/tsutils#142]
When I try to run `eslint` from the root of my workspace, I am presented the following error from `tsutils`.

```
yarn eslint ./project/packages/project-chai/src

Oops! Something went wrong! :(

ESLint: 8.10.0

TypeError: Failed to load plugin '@typescript-eslint' declared in '.eslintrc.js': Cannot read properties of undefined (reading 'split')
Referenced from: /usr/src/project/.eslintrc.js
    at Object.<anonymous> (/usr/src/node_modules/tsutils/util/util.js:1573:109)
    at Module._compile (/usr/src/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (/usr/src/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/usr/src/node_modules/tsutils/util/index.js:4:22)
    at Module._compile (/usr/src/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10)


```

If I debug the above, I can see that typescript is an empty object `{}` at line 1573 in `/usr/src/node_modules/tsutils/util/util.js`.

```js
// `ts` is `{}` here
const isTsBefore43 = (([major, minor]) => major < '4' || major === '4' && minor < '3')(ts.versionMajorMinor.split('.')
```

But `typescript` is installed and so are the various `@typescript-eslint` plugins:

```
yarn info typescript
└─ typescript@patch:typescript@npm%3A4.6.2#~builtin<compat/typescript>::version=4.6.2&hash=bda367
   ├─ Version: 4.6.2
   │
   └─ Exported Binaries
      ├─ tsc
      └─ tsserver
```

```
 yarn info @typescript-eslint/parser
└─ @typescript-eslint/parser@npm:5.13.0
   ├─ Instances: 1
   ├─ Version: 5.13.0
   │
   └─ Dependencies
      ├─ @typescript-eslint/scope-manager@npm:5.13.0 → npm:5.13.0
      ├─ @typescript-eslint/types@npm:5.13.0 → npm:5.13.0
      ├─ @typescript-eslint/typescript-estree@npm:5.13.0 → npm:5.13.0
      └─ debug@npm:^4.3.2 → npm:4.3.3


```
```
yarn info @typescript-eslint/eslint-plugin
└─ @typescript-eslint/eslint-plugin@npm:5.13.0
   ├─ Instances: 1
   ├─ Version: 5.13.0
   │
   └─ Dependencies
      ├─ @typescript-eslint/scope-manager@npm:5.13.0 → npm:5.13.0
      ├─ @typescript-eslint/type-utils@npm:5.13.0 → npm:5.13.0
      ├─ @typescript-eslint/utils@npm:5.13.0 → npm:5.13.0
      ├─ debug@npm:^4.3.2 → npm:4.3.3
      ├─ functional-red-black-tree@npm:^1.0.1 → npm:1.0.1
      ├─ ignore@npm:^5.1.8 → npm:5.2.0
      ├─ regexpp@npm:^3.2.0 → npm:3.2.0
      ├─ semver@npm:^7.3.5 → npm:7.3.5
      └─ tsutils@npm:^3.21.0 → npm:3.21.0
```

Why would `const ts = require("typescript");^M` be failing to import `typescript` in `tsutils`?

**Comment by forgetso** [comment]
This was because I'd deleted the typescript folder in node_modules and then un-deleted it with my IDE. The following sorted it out, presumably fixing any missing symlinks in the process:

```bash
rm -rf node_modules;
yarn clean cache;
yarn
```
